let templateTypes = {};

templateTypes.CONFIRM_SIGNUP = "CONFIRM_SIGNUP";
templateTypes.RECOVERY_LINK = "RECOVERY_LINK";
templateTypes.CONFIRM_RECOVERY = "CONFIRM_RECOVERY";
templateTypes.CONFIRM_ACTIVATION = "CONFIRM_ACTIVATION";
templateTypes.WELCOME_MESSAGE = "WELCOME_MESSAGE";
templateTypes.CONFIRM_PROFILE_UPDATE = "CONFIRM_PROFILE_UPDATE";
templateTypes.CONFIRM_PASSWORD_CHANGE = "CONFIRM_PASSWORD_CHANGE";

module.exports = templateTypes;
