let types = {};

types.CONFIRM_SIGNUP = "CONFIRM_SIGNUP";
types.CONFIRM_ACTIVATION = "CONFIRM_ACTIVATION";
types.CONFIRM_RECOVERY = "CONFIRM_RECOVERY";
types.CONFIRM_PASSWORD_CHANGE = "CONFIRM_PASSWORD_CHANGE";
types.CONFIRM_PROFILE_UPDATE = "CONFIRM_PROFILE_UPDATE";
types.RECOVERY_LINK = "RECOVERY_LINK";

module.exports = types;
